version: "3.6"

services:
  backend:
    container_name: ${PROJECT_NAME}_backend
    image: openizer/node:1.0.1-dev
    env_file:
      - .env
    ports:
      - "127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}"
    command: sh -c "yarn install && yarn run dev"
    volumes:
      - ./backend:/var/www/html
    restart: on-failure
  frontend:
    container_name: ${PROJECT_NAME}_frontend
    image: openizer/node:1.0.1-dev
    env_file:
      - .env
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: sh -c "yarn install && yarn run dev"
    volumes:
      - ./frontend:/var/www/html
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
